Réduit les requêtes doubles sur les auteurs et antispam
Situphen/zds-site pull request #11
Opened 2021-04-20 19:52 UTC by artragis

Quelques optimisations supplémentaires sur les tutos, notamment sur les requêtes en doubles sur les auteurs (impacte tout le monde) et sur l'antispam (uniquement les connecté)

2021-04-22 16:35 UTC, Situphen commented on zds/utils/templatetags/displayable_authors.py
> +    if hasattr(content, "public_authors"):
Je pense que cette ligne pose soucis car `content` n'a pas d'attribut `public_authors`, si ? Aussi je me demande si ça ne modifie pas le comportement car tu peux très bien vouloir afficher la version brouillon d'un contenu qui est actuellement publié. Donc je propose de garder `online` comme indicateur ça me parait plus prudent.

2021-04-22 16:35 UTC, Situphen commented on zds/tutorialv2/models/database.py
> +    def __user_last_note(self, user):
Un petit *docstring* serait pas mal je pense car c'est assez mystérieux quand on n'a pas le contexte amha.

2021-04-22 16:35 UTC, Situphen commented on templates/tutorialv2/view/content.html
> +                    {% if content.redacting_authors.count > 1 %}
Étant donné que `redacting_authors` est une liste, je ne crois pas que `.count` fonctionne. Si ça ne fonctionne pas, alors ceci devrait fonctionner : 
```suggestion
                    {% if content.redacting_authors|length > 1 %}
```

2021-04-22 16:35 UTC, Situphen commented on templates/tutorialv2/view/content.html
> +                        {% blocktrans with plural=content.redacting_authors.count|pluralize_fr %}
Étant donné que `redacting_authors` est une liste, je ne crois pas que `.count` fonctionne. Si ça ne fonctionne pas, alors ceci devrait fonctionner : 
```suggestion
                        {% blocktrans with plural=content.redacting_authors|length|pluralize_fr %}
```

2021-04-22 16:35 UTC, Situphen commented on templates/tutorialv2/view/container_online.html
> +    {% if not user in content.redacting_authors.all and user.is_authenticated %}
```suggestion
    {% if not user in content.redacting_authors and user.is_authenticated %}
```

2021-04-22 16:35 UTC, Situphen commented on templates/tutorialv2/validation/opinions.html
> +                                    {% for author in content.redacting_authors.all %}
```suggestion
                                    {% for author in content.redacting_authors %}
```

2021-04-22 20:11 UTC, artragis commented on zds/utils/templatetags/displayable_authors.py
> +    if hasattr(content, "public_authors"):
oui c'était une erreur

2021-04-25 13:58 UTC, Situphen requested changes
Je t'avoue que cette solution ressemble un peu trop à du colmatage à mes yeux, mais en même temps ça fonctionne et je ne vois pas comment faire mieux pour l'instant donc allons-y !

Il y a seulement un petit changement à effectuer et c'est bon je pense.

2021-04-25 13:58 UTC, Situphen commented on zds/tutorialv2/models/database.py
> +            self._authors = list(self.authors.all())
Je suggère ceci pour que la requête ne soit faite en base de données que si `redacting_authors()` est appelée plus loin dans le code.
```suggestion
            delattr(self, "_authors")
```

2021-04-25 13:58 UTC, Situphen commented on zds/tutorialv2/models/database.py
> +            self._authors = list(self.authors.all())
Je suggère ceci pour que la requête ne soit faite en base de données que si `public_authors()` est appelée plus loin dans le code.
```suggestion
            delattr(self, "_authors")
```

2021-04-25 14:09 UTC, Situphen approved these changes

2021-04-25 14:25 UTC, merged